# Generated by Django 2.0.2 on 2019-02-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_image',
            field=models.FileField(default=None, upload_to='images/countries/', verbose_name='FlagImage'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=models.ImageField(default=None, upload_to='images/countries/', verbose_name='Image'),
        ),
    ]
