# Generated by Django 2.0.2 on 2019-01-13 16:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('summary', models.CharField(default='', max_length=255, verbose_name='Summary')),
                ('body', tinymce.models.HTMLField(verbose_name='Content')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('pub_date', models.DateTimeField(verbose_name='PublicDate')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
